/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MastodonShareButton {
    'close_button': string;
    'instances': string;
    'modal_title': string;
    'open': boolean;
    'other_instance_text': string;
    'send_button': string;
    'share_button': string;
    'share_message': string;
    'transparent': boolean;
  }
}

declare global {


  interface HTMLMastodonShareButtonElement extends Components.MastodonShareButton, HTMLStencilElement {}
  var HTMLMastodonShareButtonElement: {
    prototype: HTMLMastodonShareButtonElement;
    new (): HTMLMastodonShareButtonElement;
  };
  interface HTMLElementTagNameMap {
    'mastodon-share-button': HTMLMastodonShareButtonElement;
  }
}

declare namespace LocalJSX {
  interface MastodonShareButton {
    'close_button'?: string;
    'instances'?: string;
    'modal_title'?: string;
    'open'?: boolean;
    'other_instance_text'?: string;
    'send_button'?: string;
    'share_button'?: string;
    'share_message'?: string;
    'transparent'?: boolean;
  }

  interface IntrinsicElements {
    'mastodon-share-button': MastodonShareButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mastodon-share-button': LocalJSX.MastodonShareButton & JSXBase.HTMLAttributes<HTMLMastodonShareButtonElement>;
    }
  }
}


