/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface MastodonButton {
    'text': string;
  }
  interface MastodonModal {
    'activated': boolean;
    'instances': any;
    'open': boolean;
    'share_text': string;
    'transparent': boolean;
  }
  interface MastodonShareButton {
    'button_text': string;
    'close_text': string;
    'instances': any;
    'modal_active': boolean;
    'share_text': string;
  }
}

declare global {


  interface HTMLMastodonButtonElement extends Components.MastodonButton, HTMLStencilElement {}
  var HTMLMastodonButtonElement: {
    prototype: HTMLMastodonButtonElement;
    new (): HTMLMastodonButtonElement;
  };

  interface HTMLMastodonModalElement extends Components.MastodonModal, HTMLStencilElement {}
  var HTMLMastodonModalElement: {
    prototype: HTMLMastodonModalElement;
    new (): HTMLMastodonModalElement;
  };

  interface HTMLMastodonShareButtonElement extends Components.MastodonShareButton, HTMLStencilElement {}
  var HTMLMastodonShareButtonElement: {
    prototype: HTMLMastodonShareButtonElement;
    new (): HTMLMastodonShareButtonElement;
  };
  interface HTMLElementTagNameMap {
    'mastodon-button': HTMLMastodonButtonElement;
    'mastodon-modal': HTMLMastodonModalElement;
    'mastodon-share-button': HTMLMastodonShareButtonElement;
  }
}

declare namespace LocalJSX {
  interface MastodonButton {
    'text'?: string;
  }
  interface MastodonModal {
    'activated'?: boolean;
    'instances'?: any;
    'onCloseModalEventCompleted'?: (event: CustomEvent<any>) => void;
    'open'?: boolean;
    'share_text'?: string;
    'transparent'?: boolean;
  }
  interface MastodonShareButton {
    'button_text'?: string;
    'close_text'?: string;
    'instances'?: any;
    'modal_active'?: boolean;
    'share_text'?: string;
  }

  interface IntrinsicElements {
    'mastodon-button': MastodonButton;
    'mastodon-modal': MastodonModal;
    'mastodon-share-button': MastodonShareButton;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'mastodon-button': LocalJSX.MastodonButton & JSXBase.HTMLAttributes<HTMLMastodonButtonElement>;
      'mastodon-modal': LocalJSX.MastodonModal & JSXBase.HTMLAttributes<HTMLMastodonModalElement>;
      'mastodon-share-button': LocalJSX.MastodonShareButton & JSXBase.HTMLAttributes<HTMLMastodonShareButtonElement>;
    }
  }
}


